### ISSUE TITLE
Support oneof messages

### ISSUE THREAD

**Issue by johanbrandhorst** [mwitkow/go-proto-validators#10]
Currently when generating code for protofiles with `oneof` message types, the code doesn't reflect what type of message it is performing the validation on, instead using the `oneof` variable directly, like so:

```
message Value {
    oneof type {
        uint64 my_uint = 1 [(validator.field) = {int_gt: 0}];
    }
}
```

```go
func (this *Value) Validate() error {
	if !(this.Type > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must must be greater than '0'`, this.Type))
	}
	return nil
}
```

This should instead be checking specific requirements for specific messages or variables within the `oneof` struct.

**Comment by mwitkow** [comment]
Indeed, `oneof` was half-working in `golang` upstream when I wrote this.

What do you think should be the semantics of `oneof`? Validate the value that is used and require it being correctly validated?

**Comment by johanbrandhorst** [comment]
Yeah, just check the type of the message and if run Validate on it if it implements the interface.
