### ISSUE TITLE
Support validation of double types

### ISSUE THREAD

**Issue by johanbrandhorst** [mwitkow/go-proto-validators#11]
I've got a proto message with a `double` variable that I would like to restrict to values between 0 and 0.1. Unfortunately this isn't possible with int_gt and int_lt, for obvious reasons. However, not even restricting it to anything between 0 and 1 exclusive works, e.g.

```
double my_double = 1 [
    (validator.field) = {
        int_gt: 0,
        int_lt: 1,
    }
];
```

Produces nothing for double fields. Presumably they're explicitly unsupported?

**Comment by mwitkow** [comment]
Yes, doubles aren't supported because I didn't have the time to implement that, expecting issues with floating point accuracy of comparison (e.g. adding an epsilon).

Would happily accept PRs to add support though :)

**Comment by johanbrandhorst** [comment]
I took a stab at it, no epsilon support yet. I expect I will have to iterate on it, any feedback is welcome.

**Comment by mwitkow** [comment]
So https://github.com/mwitkow/go-proto-validators/pull/15 also contributed to this, so we have now full float support :)

Thanks @johanbrandhorst and @Helcaraxan :)
