### ISSUE TITLE
Publish to buf schema register

### ISSUE THREAD

**Issue by palash25** [mwitkow/go-proto-validators#116]
Is it possible to have this plugin published to https://docs.buf.build/bsr/introduction  ?

I am moving my project from protoc to buf but I also use go-proto-validators and its a bit cumbersome trying to make the two work together.

**Comment by s4l1h** [comment]
@palash25 I published https://buf.build/akm/go-proto-validators

**Comment by s4l1h** [comment]
@palash25 I published https://buf.build/akm/go-proto-validators

**Comment by palash25** [comment]
thank you. i will close this then.
