### ISSUE TITLE
Using go-proto-validators prevents the use of the variable name "Validate"

### ISSUE THREAD

**Issue by johanbrandhorst** [mwitkow/go-proto-validators#19]
Simply because `Validate` is a function being defined on each struct, it means proto message with a variable called `validate` will create invalid go code (it will both have a member `Validate` and a function `Validate`). I believe this is why `gogo/protobuf` chooses functions and variables that look a bit weird (`dAtA` is one).

**Comment by johanbrandhorst** [comment]
Obviously fixing this issue would affect any packages that depend on the method being called `Validate`, and so break backwards compatibility.

**Comment by mwitkow** [comment]
This is the relevant PR:
https://github.com/mwitkow/go-proto-validators/pull/20

Yeah. I guess that would work, but it would break all the usages of `Validate` before. For example:
https://github.com/mwitkow/go-grpc-middleware/tree/master/validator

I'd rather wait and see how many people run into a similar problem.

But thanks for raising the bug @johanbrandhorst :) Appreciated.

**Comment by mwitkow** [comment]
Yea, would prefer not breaking `Validate` interface ATM.
