### ISSUE TITLE
Please make tag / releases

### ISSUE THREAD

**Issue by AlekSi** [mwitkow/go-proto-validators#29]
This will help with vendoring.

**Comment by mwitkow** [comment]
Yup. I will do it once the official vendoring tooling is decided upon..

**Comment by AlekSi** [comment]
Both vgo and dep (and pretty much all other vendoring tools) use SemVer-style tags like `v0.5.0`. You don't have to wait to add them.

**Comment by AlekSi** [comment]
Bump. Adding tags with `0` as a major version is safe. `v0.5.0` could be a good start.

**Comment by Helcaraxan** [comment]
Hello @AlekSi. I have just picked up the maintenance of this repository. I'm addressing some of the outstanding issues and will create a tag once that's done. I've already moved this project to be a Go module.

**Comment by Helcaraxan** [comment]
I have just made an initial `v0.1.0` tag available for use.

Closing this issue now. Will continue to make new tags / releases when relevant and new features / bugfixes are merged.
