### ISSUE TITLE
oneof: adding a "required" validation

### ISSUE THREAD

**Issue by jan-g** [mwitkow/go-proto-validators#30]
Am I missing a trick, or is there currently no way to enforce that a oneof field *must* have one of the contained types? Currently the generated validator falls through to return a nil error if none of the union type members are present.

**Comment by mwitkow** [comment]
Agreed this would be great. Happy to accept PRs @devnev and @johanbrandhorst for context

**Comment by scele** [comment]
@mwitkow would you have time to review my PR for this issue?
