### ISSUE TITLE
Issue parsing regex => improve docs and error message

### ISSUE THREAD

**Issue by lukasmalkmus** [mwitkow/go-proto-validators#32]
I wanted to use `go-proto-validators` to validate the field of a message by using regular expressions. This is the regular expression I used: `[\p{L}\p{N}]({\p{L}\p{N}_- ]{0,28}[\p{L}\p{N}])?.`

And... It didn't work as expected. Why? The regex isn't valid, because you can't use `\` in a string `"`. Take a look at the generated code:
```
regexp.MustCompile("[\p{L}\p{N}]({\p{L}\p{N}_- ]{0,28}[\p{L}\p{N}])?.") # Does panic!
```
You need to escape the backtick with another one: `[\\p{L}\\p{N}]({\\p{L}\\p{N}_- ]{0,28}[\\p{L}\\p{N}])?.`. This works, but also produces and ugly error message.

I can't decide if this should be treated like an error or not. But we should at least put a note in the README.

**Comment by mwitkow** [comment]
Ok, this sounds like whatever we're parsing from protobuf field options should be escaped into the `MustCompile` string, or the `MustCompile` codegen should be using `"""`. Fancy taking a stab at fixing this?

**Comment by lukasmalkmus** [comment]
Take a look at #36. I would love some feedback and additional testing.
