### ISSUE TITLE
msg_exists for repeated fields

### ISSUE THREAD

**Issue by bvisness** [mwitkow/go-proto-validators#33]
Why can't `msg_exists` be used for repeated fields? Since other validators can be used on repeated fields, I would expect `msg_exists` to work as well.

For example, using regex on a repeated string field loops through the strings and validates each one, but using msg_exists on a repeated message field results in a warning and no validation:

```
message Test {
    repeated string foo = 1 [(validator.field) = {string_not_empty: true}];
    repeated Test bar = 2 [(validator.field) = {msg_exists: true}];
}
```

```go
func (this *Test) Validate() error {
	for _, item := range this.Foo {
		if item == "" {
			return go_proto_validators.FieldError("Foo", fmt.Errorf(`value '%v' must not be an empty string`, item))
		}
	}
	for _, item := range this.Bar {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("Bar", err)
			}
		}
	}
	return nil
}
```

```
WARNING: field Test.Bar is repeated, validator.msg_exists has no effect
```

**Comment by mwitkow** [comment]
Well `msg_exists` is there for optional fields as a simple replacement for lack of `required`. But `repeated_count_min` is what you'd need here:
https://github.com/mwitkow/go-proto-validators/blob/master/validator.proto#L56
