### ISSUE TITLE
protobuffer url seams to have changed

### ISSUE THREAD

**Issue by pmalhaire** [mwitkow/go-proto-validators#56]
In the readme the path to protobuf is 

```
	--proto_path=${GOPATH}/src/github.com/google/protobuf/src 
```

the url seems to have moved to https://github.com/protocolbuffers/protobuf

**Comment by Helcaraxan** [comment]
Sorry for the (very) late reply to your point. This is actually not a change that has been made. Although the _repository_ has indeed moved to the address you are referencing the tree-path of the canonical proto files has not changed and is still `src/google/protobuf` as you can see [here](https://github.com/protocolbuffers/protobuf/tree/v3.8.0/src/google/protobuf).
