### ISSUE TITLE
Import "github.com/mwitkow/go-proto-validators/validator.proto" was not found or had errors.

### ISSUE THREAD

**Issue by payalord** [mwitkow/go-proto-validators#75]
Hi, I faced next error, when i run `protoc` command:
```
github.com/mwitkow/go-proto-validators/validator.proto: File not found.
Import "github.com/mwitkow/go-proto-validators/validator.proto" was not found or had errors.
```
protoc version: libprotoc 3.9.1
go version: 1.13
protoc-gen-go installed as it said in instuctions here: https://developers.google.com/protocol-buffers/docs/gotutorial via this command:
```
go get -u github.com/golang/protobuf/protoc-gen-go
```
I also installed this:
```
go get github.com/mwitkow/go-proto-validators/protoc-gen-govalidators
```
But i think this last is not related to my main problem here that I mentioned on top.

**Comment by payalord** [comment]
Actually this error happened on go version: 1.12 too, I just upgraded it to 1.13. So for both of this version this error happens.

**Comment by liuxuisme** [comment]
I also encountered, how to solve this problem

**Comment by Helcaraxan** [comment]
Hello @payalord and @liuxuisme.

Thank you for raising the issue!

Would it be possible to get a bit more information about the manner in which you are both invoking the `protoc` compile? With the information that you currently provide I can't narrow down the list of potential causes of the error that you are seeing. And these potential causes cover a too vast area to explicitly list them up front.

Ideally I would have:
- The folder structure that contains the proto files you are compiling.
- The exact `protoc` command you are invoking.
- The output of `go env` when run at the location where you called
  ```
  go get -u github.com/golang/protobuf/protoc-gen-go
  ```

**Comment by liuxuisme** [comment]
My own problem. This tool is great, my bro

**Comment by liuxuisme** [comment]
> Hello @payalord and @liuxuisme.
> 
> Thank you for raising the issue!
> 
> Would it be possible to get a bit more information about the manner in which you are both invoking the `protoc` compile? With the information that you currently provide I can't narrow down the list of potential causes of the error that you are seeing. And these potential causes cover a too vast area to explicitly list them up front.
> 
> Ideally I would have:
> 
> * The folder structure that contains the proto files you are compiling.
> * The exact `protoc` command you are invoking.
> * The output of `go env` when run at the location where you called
>   ```
>   go get -u github.com/golang/protobuf/protoc-gen-go
>   ```

My own problem. This tool is great, my bro

**Comment by Helcaraxan** [comment]
That's good to hear @liuxuisme. Great that you got solved the issue. 👍

**Comment by Dieyin** [comment]
I have also encountered this problem. I have been trapped for two days. How can I solve it, brother

**Comment by fidelyiu** [comment]
> I have also encountered this problem. I have been trapped for two days. How can I solve it, brother

Here are the steps I took to solve the problem.
1. First make sure your environment version is consistent with the documentation
2. Modify the import
```protobuf
syntax = "proto3";
package validator.examples;
import "validator.proto";
option go_package="./YiuProto";

message InnerMessage {
  // some_integer can only be in range (0, 100).
  int32 some_integer = 1 [(validator.field) = {int_gt: 0, int_lt: 100}];
  // some_float can only be in range (0;1).
  double some_float = 2 [(validator.field) = {float_gte: 0, float_lte: 1}];
}

message OuterMessage {
  // important_string must be a lowercase alpha-numeric of 5 to 30 characters (RE2 syntax).
  string important_string = 1 [(validator.field) = {regex: "^[a-z0-9]{5,30}$"}];
  // proto3 doesn't have `required`, the `msg_exist` enforces presence of InnerMessage.
  InnerMessage inner = 2 [(validator.field) = {msg_exists : true}];
}

```


3. Execute the correct command line
```bash
protoc   \
        -I=F:/GoCode/pkg/mod/github.com/mwitkow/go-proto-validators@v0.3.2/  \
        -I=.  \
        --go_out=.  \
        --go_opt=paths=source_relative  \
        --govalidators_out=.  \
        --govalidators_opt=paths=source_relative  \
        *.proto
```

Use the `-I` argument to identify where import needs to be found for protoc compilation.
